In [1]:
import numpy as np
import pandas as pd
import requests
from bs4 import BeautifulSoup

In [10]:
#company doesnt want to share api to get data so we do web srcaping
webpage = requests.get(
    "https://www.ambitionbox.com/list-of-companies?campaign=desktop_nav",
    headers=headers,
    timeout=10
).text

soup = BeautifulSoup(webpage, "lxml")

In [12]:
# print(soup.prettify())
soup.find_all('h1') #-> llist
# soup.find_all('h1')[0].text

[<h1 class="companyListing__collectionTopHeadingCont" data-v-bb58b91c=""><div class="companyListing__collectionTopHeading" data-v-bb58b91c="">
 					Top Companies in
 				</div> <div class="companyListing__collectionIndiaHeading" data-v-bb58b91c=""><img data-v-bb58b91c="" height="12" src="https://static.ambitionbox.com/static/loc/loc-star.png" width="12"/>
 					INDIA
 					<img data-v-bb58b91c="" height="12" src="https://static.ambitionbox.com/static/loc/loc-star.png" width="12"/></div></h1>]

In [27]:
company=soup.find_all('div',class_='companyCardWrapper')

In [18]:
for i in soup.find_all('h2'):
    print(i.text.strip())

Companies in India
TCS
Accenture
Wipro
Cognizant
Capgemini
HDFC Bank
Infosys
HCLTech
ICICI Bank
Tech Mahindra
Genpact
TP
Axis Bank
Jio
Concentrix Corporation
Amazon
Reliance Retail
iEnergizer
LTM Limited
HDB Financial Services
Popular Collections by Industries
Popular Collections by Cities
Popular Collections by Roles

In [26]:
ratings=(soup.find_all(class_='rating_text'))
for rating in ratings:
    print(rating.text.strip())

3.3
3.7
3.6
3.7
3.6
3.8
3.5
3.4
4.0
3.3
3.6
3.9
3.6
4.4
3.5
3.9
3.9
4.5
3.6
3.9

In [43]:
name=[]
rating=[]
reviews=[]
ctype=[]
hq=[]
old=[]
employees=[]

for i in company:
    name.append(i.find('h2').text.strip())
    rating.append(i.find(class_='rating_text').text.strip())
    reviews.append(i.find(class_="companyCardWrapper__ActionCount").text.strip())   

d={'Name':name, 'rating':rating , 'reviews':reviews}
df=pd.DataFrame(d)

In [33]:
reviews

['1.2L',
 '75.7k',
 '66.8k',
 '63.1k',
 '55.2k',
 '54.3k',
 '50.2k',
 '47.4k',
 '46.9k',
 '44.5k',
 '43.7k',
 '39.9k',
 '34.4k',
 '34.2k',
 '33.1k',
 '32.6k',
 '27.9k',
 '27.7k',
 '27.3k',
 '26.4k']

In [41]:
company[0].find_all('span',class_='companyCardWrapper__interLinking')

[<span class="companyCardWrapper__interLinking">
 							IT Services &amp; Consulting | Bengaluru +476 other locations
 						</span>]

In [44]:
df

                      Name rating reviews
0                      TCS    3.3    1.2L
1                Accenture    3.7   75.7k
2                    Wipro    3.6   66.8k
3                Cognizant    3.7   63.1k
4                Capgemini    3.6   55.2k
5                HDFC Bank    3.8   54.3k
6                  Infosys    3.5   50.2k
7                  HCLTech    3.4   47.4k
8               ICICI Bank    4.0   46.9k
9            Tech Mahindra    3.3   44.5k
10                 Genpact    3.6   43.7k
11                      TP    3.9   39.9k
12               Axis Bank    3.6   34.4k
13                     Jio    4.4   34.2k
14  Concentrix Corporation    3.5   33.1k
15                  Amazon    3.9   32.6k
16         Reliance Retail    3.9   27.9k
17              iEnergizer    4.5   27.7k
18             LTM Limited    3.6   27.3k
19  HDB Financial Services    3.9   26.4k

In [45]:
df.shape

(20, 3)

In [52]:
final=pd.DataFrame()
for j in range (1,11):
    url=f'https://www.ambitionbox.com/list-of-companies?page={j}'
    webpage = requests.get(
    url,
    headers=headers,
    timeout=10
    ).text

    soup = BeautifulSoup(webpage, "lxml")
    company=soup.find_all('div',class_='companyCardWrapper')
    name=[]
    rating=[]
    reviews=[]
    ctype=[]
    hq=[]
    old=[]
    employees=[]
    
    for i in company:
        name.append(i.find('h2').text.strip())
        rating.append(i.find(class_='rating_text').text.strip())
        reviews.append(i.find(class_="companyCardWrapper__ActionCount").text.strip())   
    
    d={'Name':name, 'rating':rating ,
 'reviews':reviews}
    df=pd.DataFrame(d)
    final = pd.concat([final, df], ignore_index=True)

In [53]:
final

                                Name rating reviews
0                                TCS    3.3    1.2L
1                          Accenture    3.7   75.7k
2                              Wipro    3.6   66.8k
3                          Cognizant    3.7   63.1k
4                          Capgemini    3.6   55.2k
..                               ...    ...     ...
195  Aditya Birla Sun Life Insurance    4.0    4.1k
196                Grasim Industries    4.0    4.1k
197                  Bank of America    4.1      4k
198                      PNB MetLife    3.3      4k
199                 American Express    4.1      4k

[200 rows x 3 columns]